### ISSUE TITLE
Remove dependency to external micropython-ulogging package

### ISSUE THREAD

**Issue by brainelectronics** [brainelectronics/micropython-modules#20]
To become independent from other external packages, the `micropython-ulogging` shall be remove

- Add `ulogging` file to `be_helpers` with latest version of https://github.com/micropython/micropython-lib/blob/7128d423c2e7c0309ac17a1e6ba873b909b24fcc/python-stdlib/logging/logging.py
- Remove dependency from `setup.py`

**Comment by xlla** [comment]
why not use external logging from micropython-lib, then user can control logger behaviour in different modules with unified configuration, such as write to file or change formatter.
